name: portai-master

networks:
  master-netwrk:
    external: true

services:
  portai-master-io:
    container_name: portai-master-io
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ../../.env
    ports:
      - ${PORTAI_NERGUI_EA_PORT}:${PORTAI_NERGUI_EA_PORT_OF}
      - ${PORTAI_NERGUI_UI_PORT}:${PORTAI_NERGUI_UI_PORT_OF}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portai-master-da:/data
    networks:
      - master-netwrk

volumes:
  portai-master-da:
